#!/bin/bash

# Watch for changes in directories and reconfigure nginx
DATADIR=${DATADIR:-/data}

function change_vhost() {
local _dir _suffix _vhost _template
    _dir=$1
    if [[ $_dir =~ \. ]]
    then
        _suffix="${_dir##*.}"
        _template="plain"
        if [[ -f /template/${_suffix} ]]
        then
            _template="${_suffix}"
            _vhost="${_dir%.${_suffix}}"
        else
            _vhost="$dir"
        fi
        echo "Vhost: ${_vhost} Template: ${_template}"
    fi
}
function refresh_vhost() {
    echo "REFRESH: $1"
}
while read event dir
do
    
    if [[ -n $dir ]] && [[ $event =~ ,ISDIR$ ]]
    then
        case $event in
            ATTRIB,ISDIR)
                refresh_vhost "$dir"
                ;;
            CREATE,ISDIR|MOVED_FROM,ISDIR|MOVED_TO,ISDIR|DELETE,ISDIR)
                change_vhost "$dir"
                ;;
              *)
                :
                #echo OTHER EVENT: e: $event dir: $dir
        esac
    fi
done < <(inotifywait -m -q --format '%e %f' ${DATADIR})
# vim: set tabstop=4 shiftwidth=4 expandtab autoindent indentexpr= nosmartindent :
